# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lee Huffman
description: >- # this means to ignore newlines until "baseurl:"
  Lee Huffman: GitHub, Wild Buffalo House of Music, Bellingham Engraving,
  Milk + Honey Crew
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark

# Profile information
name: Lee Huffman
tagline: Bellingham, WA.
about-description: SRE Data Center at GitHub, Co-Owner at Wild Buffalo House of Music, Partner at Bellingham Engraving,
  Founder at Milk + Honey Crew, Real Estate.
pic: me.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: lee.huffman@gmail.com
website: leehuffman.io
linkedin: iamleehuffman
github: leehuffman
twitter: leehuffman

# Build settings
markdown: kramdown
remote_theme: artemsheludko/monday
plugins:
  - jekyll-feed

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets
